services:
  k6:
    command: ["run", "/app/test.ts"]
    environment:
      K6_WEB_DASHBOARD: true
      K6_WEB_DASHBOARD_HOST: 0.0.0.0
      K6_WEB_DASHBOARD_PERIOD: 5s
      K6_WEB_DASHBOARD_EXPORT: /app/tmp/k6/k6_export.html
    image: grafana/k6:1.6.1
#    ports:
      # - "5665:5665" for web dashboard
    profiles:
      - load
    volumes:
      - ../k6:/app
