version: "2"
run:
  allow-parallel-runners: true
  allow-serial-runners: true
  build-tags:
    - wireinject
output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    #    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - errcheck
        text: .Close
      - linters:
          - varnamelen
        text: variable name 'ok' is too short for the scope of its usage
      - linters:
          - unused
        text: type `validationError` is unused
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
      - linters:
          - ireturn
        path: .*handlers.*
      - linters:
          - ireturn
          - nonamedreturns
        path: .*middlewares.*
      - linters:
          - ireturn
          - nonamedreturns
        path: .*interceptors.*
      - linters:
          - gochecknoinits
        path: .*cmd.*
      - linters:
          - funlen
        path: .*_test\.go

    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  whole-files: true
  fix: true
severity:
  default: error
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
