#schema: https://taskfile.dev/schema.json
version: '3.17'

tasks:
  lint:
    desc: Линт
    cmds:
      - golangci-lint run

  test:
    desc: Запустить тесты
    cmds:
      - go test ./... {{.CLI_ARGS}}

  bench:
    desc: Запустить бенчмарки
    cmds:
      - go test ./... -bench . -benchmem