include:
  - ../observability/docker-compose.yml

services:
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "127.0.0.1:${DOCKER_PORT_PYROSCOPE:?}:4040"

volumes:
  grafana_data:
  prometheus_data:
