services:
  pyroscope:
    image: grafana/pyroscope:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DOCKER_PORT_PYROSCOPE:?}:4040"

  db-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    environment:
      DATA_SOURCE_URI: "db:5432/${DB_DATABASE:?}?sslmode=disable"
      DATA_SOURCE_USER: ${DB_USERNAME:?}
      DATA_SOURCE_PASS: ${DB_PASSWORD:?}
    ports:
      - "127.0.0.1:${DOCKER_PORT_POSTGRES_EXPORTER:?}:9187"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9187/metrics" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-exporter:
    image: oliver006/redis_exporter:v1.81.0-alpine
    restart: unless-stopped
    environment:
      - REDIS_ADDR=${REDIS_URL:?}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPORTER_CHECK_SINGLE_STREAMS=comments_unprocessed
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9121/metrics" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-insight:
    image: redis/redisinsight:3.2.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DOCKER_PORT_REDIS_INSIGHT:?}:5540"
    volumes:
      - redisinsight:/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "5540" ]
      interval: 10s
      timeout: 5s
      retries: 3

  scrapper:
    image: victoriametrics/vmagent:latest
    restart: unless-stopped
    command:
      - '-promscrape.config=/etc/vmagent/scrapper.yml'
      - '-remoteWrite.url=${OBSERVABILITY_PROMETHEUS_REMOTE_WRITE_URL:?}'
      - '-remoteWrite.headers=${OBSERVABILITY_OTLP_TOKEN_KEY}: ${OBSERVABILITY_OTLP_TOKEN_VALUE:?}'
    volumes:
      - ./.docker/observability/scrapper.yml:/etc/vmagent/scrapper.yml:ro
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'


volumes:
  redisinsight:
  prometheus_data:
