#schema: https://taskfile.dev/schema.json
version: '3.17'

env:
  DOCKER_HOST_UID:
    sh: id -u
  DOCKER_HOST_GID:
    sh: id -g

dotenv: [
  '.env',
]

vars:
  IMAGE_BASE: gitlab.thumbrise.ru:5050/taskman/taskman-backend/base

tasks:
  # Host commands
  c:
    desc: docker compose и аргументы. Рабочий пример [task c -- up -d]. -- обязательно.
    cmd: docker compose {{.CLI_ARGS}}

  bash:
    desc: Войти в терминал app.
    cmd: task c -- exec app bash
  db:
    desc: Войти в терминал db.
    cmd: task c -- exec db bash
  up:
    desc: Тулчейн полного поднятия окружения. Вкратце, создание сети, пребилд некоторых образов и docker compose up -d.
    cmds:
      - task down

      - task c -- up -d --build --remove-orphans

      - docker image prune --force
      - docker container prune --force

  down:
    desc: Удалить все контейнеры во всех окружениях
    cmds:
      - task c -- down

  reup:
    desc: Чистый перезапуск сервиса
    cmds:
      - docker compose down {{.CLI_ARGS}}
      - docker compose up -d {{.CLI_ARGS}}

  # Container commands
  generate:
    desc: Сгенерировать необходимости
    cmds:
      - go tool swag init -g internal/modules/swagger/endpoints/http/swagger.go
      - go tool swag fmt
      - go tool wire $(go list ./... | grep -v /test)

  lint:
    desc: Линт
    cmds:
      - golangci-lint run
      - go tool swag fmt

  test:
    desc: Запустить все тесты
    cmds:
      - task: test_unit
      - task: test_e2e

  test_unit:
    desc: Запустить юнит тесты
    cmds:
      - go test $(go list ./... | grep -v /e2e) -v -tags=test

  test_e2e:
    desc: Запустить e2e тесты
    cmds:
      - go test ./internal/tests/e2e_test/... -tags=test

  load:
    desc: Load test (VREMENNO)
    interactive: true
    cmd: docker run --rm -it --network=task_manager_default
      -v ./:/app
      -e K6_WEB_DASHBOARD=true
      -e K6_WEB_DASHBOARD_HOST=0.0.0.0
      -e K6_WEB_DASHBOARD_PERIOD=5s
      -e K6_WEB_DASHBOARD_EXPORT=/app/tmp/k6/k6_export.html
      -p 5665:5665
      grafana/k6 run /app/db/loads/test.ts
