// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"github.com/thumbrise/demo/golang-demo/cmd"
)

// Injectors from container.go:

func InitializeContainer(ctx context.Context) *Container {
	kernel := cmd.NewKernel()
	container := NewContainer(kernel)
	return container
}

// container.go:

type Container struct {
	*cmd.Kernel
}

func NewContainer(kernel *cmd.Kernel) *Container {
	return &Container{Kernel: kernel}
}
