// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/thumbrise/demo/golang-demo/cmd"
	"github.com/thumbrise/demo/golang-demo/cmd/cmds"
	"github.com/thumbrise/demo/golang-demo/internal"
	"github.com/thumbrise/demo/golang-demo/internal/app"
	"github.com/thumbrise/demo/golang-demo/internal/app/core"
	"github.com/thumbrise/demo/golang-demo/internal/bootstrap"
	"github.com/thumbrise/demo/golang-demo/internal/bootstrap/container"
	"github.com/thumbrise/demo/golang-demo/internal/modules/analytics"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/application/usecases"
	http3 "github.com/thumbrise/demo/golang-demo/internal/modules/auth/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/dal"
	otp2 "github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/dal/otp"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/jwt"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/mailers"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/otp"
	"github.com/thumbrise/demo/golang-demo/internal/modules/comments"
	usecases2 "github.com/thumbrise/demo/golang-demo/internal/modules/comments/application/usecases"
	"github.com/thumbrise/demo/golang-demo/internal/modules/comments/application/workers"
	cmd2 "github.com/thumbrise/demo/golang-demo/internal/modules/comments/endpoints/cmd"
	http5 "github.com/thumbrise/demo/golang-demo/internal/modules/comments/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/homepage"
	http4 "github.com/thumbrise/demo/golang-demo/internal/modules/homepage/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/homepage/infrastucture/generator"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/database"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/http"
	components2 "github.com/thumbrise/demo/golang-demo/internal/modules/plugins/http/components"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/http/observability"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/mail"
	observability2 "github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability/components"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability/components/logger"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability/components/meter"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability/components/profiler"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/observability/components/tracer"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/redis"
	"github.com/thumbrise/demo/golang-demo/internal/modules/plugins/swagger"
	"github.com/thumbrise/demo/golang-demo/internal/modules/shared/errorsmap"
	http2 "github.com/thumbrise/demo/golang-demo/internal/modules/shared/errorsmap/endpoints/http"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context) (*container.Container, error) {
	loader := app.NewLoader()
	config := app.NewConfig(loader)
	resource, err := components.NewResource(ctx, config)
	if err != nil {
		return nil, err
	}
	otlpConfig := components.NewOTLPConfig(loader)
	exporter, err := logger.NewExporter(ctx, otlpConfig)
	if err != nil {
		return nil, err
	}
	loggerProvider := logger.NewOTELSDKProvider(resource, exporter)
	slogLogger := logger.NewLogger(config, loggerProvider)
	eventLogger := bootstrap.NewEventLogger(slogLogger)
	bootstrapper := bootstrap.NewBootstrapper(eventLogger)
	kernel := core.NewKernel()
	runner := bootstrap.NewRunner(eventLogger)
	componentsConfig := components2.NewConfig(loader)
	slogginConfig := components2.NewSlogginConfig()
	engine := components2.NewGinEngine(slogLogger, slogginConfig)
	componentsKernel := components2.NewKernel(componentsConfig, slogLogger, engine)
	serve := cmds.NewServe(kernel, runner, componentsKernel)
	route := cmds.NewRoute(kernel)
	routeList := cmds.NewRouteList(route, componentsKernel)
	v := cmd.Commands(serve, route, routeList)
	healthRouter := observability.NewHealthRouter(componentsKernel)
	otlpmetricgrpcExporter, err := meter.NewExporter(ctx, otlpConfig)
	if err != nil {
		return nil, err
	}
	meterProvider := meter.NewOTELSDKProvider(resource, otlpmetricgrpcExporter)
	provider := meter.NewProvider(config, meterProvider)
	httpMetrics := observability.NewHTTPMetrics(provider)
	profilerConfig := profiler.NewConfig(loader)
	profilerProfiler := profiler.NewProfiler(config, profilerConfig, slogLogger)
	otlptraceExporter, err := tracer.NewOTELExporter(ctx, otlpConfig)
	if err != nil {
		return nil, err
	}
	sampler := tracer.NewOTELSampler()
	stdouttraceExporter, err := tracer.NewStdOutExporter()
	if err != nil {
		return nil, err
	}
	tracerProvider := tracer.NewOTELSDKProvider(resource, otlptraceExporter, sampler, stdouttraceExporter)
	provider2 := tracer.NewProvider(config, tracerProvider)
	otelMiddleware := observability.NewOTELMiddleware(config, httpMetrics, slogLogger, profilerProfiler, provider2)
	module := http.NewModule(healthRouter, componentsKernel, otelMiddleware)
	errorHandler := components.NewErrorHandler(slogLogger)
	registrar := components.NewRegistrar(config, errorHandler, profilerProfiler, loggerProvider, meterProvider, tracerProvider)
	observabilityModule := observability2.NewModule(registrar, errorHandler)
	databaseConfig := database.NewConfig(loader)
	db := database.NewDB(databaseConfig)
	databaseModule := database.NewModule(db)
	mailModule := mail.NewModule()
	redisConfig := redis.NewConfig(loader)
	client, err := redis.NewClient(redisConfig)
	if err != nil {
		return nil, err
	}
	otelRegistrar := redis.NewOTELRegistrar(meterProvider, client, tracerProvider)
	redisModule := redis.NewModule(otelRegistrar, client)
	errorsMapMiddleware := http2.NewErrorsMapMiddleware(slogLogger)
	errorsmapModule := errorsmap.NewModule(componentsKernel, errorsMapMiddleware)
	swaggerRouter := swagger.NewSwaggerRouter(componentsKernel)
	swaggerModule := swagger.NewModule(swaggerRouter)
	mailConfig := mail.NewConfig(loader)
	otpMailer := mailers.NewOTPMail(mailConfig)
	otpConfig := otp.NewConfig(loader)
	otpGenerator := otp.NewGenerator()
	userRepository := dal.NewUserRepository(db)
	otpRedisRepository := otp2.NewOTPRedisRepository(client)
	otpPostresqlRepository := otp2.NewOTPPostgresqlRepository(db)
	authCommandSignIn := usecases.NewAuthCommandSignIn(slogLogger, otpMailer, otpConfig, otpGenerator, userRepository, otpRedisRepository, otpPostresqlRepository)
	jwtConfig := jwt.NewConfig(loader)
	jwtJWT := jwt.NewJWT(jwtConfig)
	authCommandExchangeOtp := usecases.NewAuthCommandExchangeOtp(slogLogger, jwtJWT, otpRedisRepository, userRepository)
	authQueryMe := usecases.NewAuthQueryMe(slogLogger)
	authCommandRefresh := usecases.NewAuthCommandRefresh(slogLogger, jwtJWT)
	middleware := http3.NewMiddleware(jwtJWT)
	router := http3.NewRouter(componentsKernel, authCommandSignIn, authCommandExchangeOtp, authQueryMe, authCommandRefresh, middleware, jwtJWT)
	authModule := auth.NewModule(router)
	generatorGenerator := generator.NewGenerator()
	homePageRouter := http4.NewHomePageRouter(generatorGenerator, componentsKernel)
	homepageModule := homepage.NewModule(homePageRouter)
	cmdComments := cmd2.NewComments(kernel)
	commentsBatcher := workers.NewCommentsBatcher(slogLogger)
	commentsBatch := cmd2.NewCommentsBatch(cmdComments, runner, commentsBatcher)
	commentsCommandPublish := usecases2.NewCommentsCommandPublish(slogLogger, client)
	httpRouter := http5.NewRouter(commentsCommandPublish, componentsKernel)
	commentsModule := comments.NewModule(cmdComments, commentsBatch, httpRouter)
	metrics := analytics.NewMetrics(provider, userRepository)
	analyticsModule := analytics.NewModule(metrics)
	v2 := internal.Modules(module, observabilityModule, databaseModule, mailModule, redisModule, errorsmapModule, swaggerModule, authModule, homepageModule, commentsModule, analyticsModule)
	containerContainer := container.NewContainer(bootstrapper, kernel, v, componentsKernel, v2, runner)
	return containerContainer, nil
}
