// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"context"
	"github.com/google/wire"
	"github.com/thumbrise/demo/golang-demo/cmd"
	"github.com/thumbrise/demo/golang-demo/cmd/cmds"
	"github.com/thumbrise/demo/golang-demo/internal"
	"github.com/thumbrise/demo/golang-demo/internal/bootstrap"
	"github.com/thumbrise/demo/golang-demo/internal/config"
	"github.com/thumbrise/demo/golang-demo/internal/contracts"
	"github.com/thumbrise/demo/golang-demo/internal/infrastructure/components"
	"github.com/thumbrise/demo/golang-demo/internal/infrastructure/dal"
	otp2 "github.com/thumbrise/demo/golang-demo/internal/infrastructure/dal/otp"
	"github.com/thumbrise/demo/golang-demo/internal/infrastructure/kernels/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/application/usecases"
	http4 "github.com/thumbrise/demo/golang-demo/internal/modules/auth/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/auth/infrastructure/mailers"
	"github.com/thumbrise/demo/golang-demo/internal/modules/observability"
	"github.com/thumbrise/demo/golang-demo/internal/modules/observability/endpoints/http/middlewares"
	"github.com/thumbrise/demo/golang-demo/internal/modules/observability/endpoints/http/routers"
	"github.com/thumbrise/demo/golang-demo/internal/modules/observability/infrastructure/components/profiler"
	"github.com/thumbrise/demo/golang-demo/internal/modules/observability/infrastructure/components/tracer"
	"github.com/thumbrise/demo/golang-demo/internal/modules/shared/errorsmap"
	http2 "github.com/thumbrise/demo/golang-demo/internal/modules/shared/errorsmap/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/shared/redis"
	components2 "github.com/thumbrise/demo/golang-demo/internal/modules/shared/redis/infrastructure/components"
	"github.com/thumbrise/demo/golang-demo/internal/modules/swagger"
	http3 "github.com/thumbrise/demo/golang-demo/internal/modules/swagger/endpoints/http"
	"github.com/thumbrise/demo/golang-demo/internal/modules/user"
	usecases2 "github.com/thumbrise/demo/golang-demo/internal/modules/user/application/usecases"
	routers2 "github.com/thumbrise/demo/golang-demo/internal/modules/user/endpoints/http/routers"
	"github.com/thumbrise/demo/golang-demo/pkg/env"
	"github.com/thumbrise/demo/golang-demo/pkg/otp"
	trace2 "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func InitializeContainer(ctx context.Context) (*Container, error) {
	kernel := cmd.NewKernel()
	route := cmds.NewRoute()
	loader := env.NewLoader()
	configHttp := config.NewHttp(loader)
	app := config.NewApp(loader)
	logger := components.NewLogger(app)
	httpKernel := http.NewKernel(configHttp, logger)
	routeList := cmds.NewRouteList(httpKernel)
	runner := bootstrap.NewRunner(logger)
	serve := cmds.NewServe(runner, httpKernel)
	bootloader := cmd.NewBootloader(kernel, route, routeList, serve)
	errorsMapMiddleware := http2.NewErrorsMapMiddleware(logger)
	errorsMapRouter := http2.NewErrorsMapRouter(errorsMapMiddleware, httpKernel)
	errorsmapBootloader := errorsmap.NewBootloader(errorsMapRouter)
	healthRouter := routers.NewHealthRouter(httpKernel)
	configObservability := config.NewObservability(loader)
	profilerProfiler := profiler.NewProfiler(app, configObservability, logger)
	observabilityMiddleware := middlewares.NewObservabilityMiddleware(app, configObservability, profilerProfiler, logger)
	observabilityRouter := routers.NewObservabilityRouter(httpKernel, observabilityMiddleware)
	pprofRouter := routers.NewPprofRouter(httpKernel)
	tracerProvider, err := tracer.NewTracerProvider(ctx, configObservability, app)
	if err != nil {
		return nil, err
	}
	observabilityBootloader := observability.NewBootloader(healthRouter, observabilityRouter, pprofRouter, profilerProfiler, tracerProvider)
	swaggerRouter := http3.NewSwaggerRouter(httpKernel)
	swaggerBootloader := swagger.NewBootloader(swaggerRouter)
	mail := config.NewMail(loader)
	otpMailer := mailers.NewOTPMail(mail)
	configAuth := config.NewAuth(loader)
	generator := otp.NewGenerator()
	db := config.NewDB(loader)
	componentsDB := components.MustConnect(ctx, db)
	userRepository := dal.NewUserRepository(componentsDB)
	redis := config.NewRedis(loader)
	client, err := components2.NewRedisClient(redis)
	if err != nil {
		return nil, err
	}
	otpRedisRepository := otp2.NewOTPRedisRepository(client)
	otpPostresqlRepository := otp2.NewOTPPostgresqlRepository(componentsDB)
	authCommandSignIn := usecases.NewAuthCommandSignIn(logger, otpMailer, configAuth, generator, userRepository, otpRedisRepository, otpPostresqlRepository)
	jwt := components.NewJWT(configAuth)
	authCommandExchangeOtp := usecases.NewAuthCommandExchangeOtp(logger, jwt, otpRedisRepository, userRepository)
	authQueryMe := usecases.NewAuthQueryMe(logger)
	authCommandRefresh := usecases.NewAuthCommandRefresh(logger, jwt)
	middleware := http4.NewMiddleware(jwt)
	router := http4.NewRouter(httpKernel, authCommandSignIn, authCommandExchangeOtp, authQueryMe, authCommandRefresh, middleware, jwt)
	authBootloader := auth.NewBootloader(logger, router)
	v := internal.Bootloaders(bootloader, errorsmapBootloader, observabilityBootloader, swaggerBootloader, authBootloader)
	container := NewContainer(v, logger, runner, httpKernel, kernel)
	return container, nil
}

// wire.go:

var sAll = wire.NewSet(internal.Bootloaders, bootstrap.NewRunner, cmd.NewBootloader, cmd.NewKernel, http.NewKernel, cmds.NewServe, cmds.NewRoute, cmds.NewRouteList, errorsmap.NewBootloader, http2.NewErrorsMapMiddleware, http2.NewErrorsMapRouter, redis.NewBootloader, components2.NewRedisClient, swagger.NewBootloader, http3.NewSwaggerRouter, observability.NewBootloader, middlewares.NewObservabilityMiddleware, routers.NewHealthRouter, routers.NewObservabilityRouter, routers.NewPprofRouter, wire.NewSet(tracer.NewTracerProvider, wire.Bind(new(trace.TracerProvider), new(*trace2.TracerProvider))), tracer.NewTracer, auth.NewBootloader, http4.NewMiddleware, http4.NewRouter, mailers.NewOTPMail, usecases.NewAuthCommandSignIn, usecases.NewAuthCommandExchangeOtp, usecases.NewAuthQueryMe, usecases.NewAuthCommandRefresh, user.NewBootloader, routers2.NewUsersRouter, usecases2.NewUserQueryOne, profiler.NewProfiler, components.NewLogger, components.NewJWT, components.MustConnect, wire.NewSet(wire.Bind(new(contracts.EnvLoader), new(*env.Loader)), env.NewLoader), wire.NewSet(wire.Bind(new(contracts.OtpGenerator), new(*otp.Generator)), otp.NewGenerator), config.NewApp, config.NewDB, config.NewMail, config.NewAuth, config.NewHttp, config.NewObservability, config.NewRedis, dal.NewUserRepository, otp2.NewOTPRedisRepository, otp2.NewOTPPostgresqlRepository)
